<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\MitMediator.AutoApi.HttpMediator\MitMediator.AutoApi.HttpMediator.csproj" />
      <ProjectReference Include="..\Server\BooksCatalog.Application\BooksCatalog.Application.csproj" />
    </ItemGroup>

    
    <PropertyGroup>
        <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
    </PropertyGroup>

    <ItemGroup>
  </ItemGroup>
</Project>
